version: '3'
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-net
  flask:
    build: .
    ports:
      - "5001:5001"
    networks:
      - app-net
    command: "flask run --host 0.0.0.0 --port 5001"
    depends_on:
      - db
    volumes:
      - ./app:/app
networks:
  app-net:
    driver: bridge